### ISSUE TITLE
Wrong indexes

### ISSUE THREAD

**Issue by ameta13** [SapienzaNLP/mcl-wic#2]
Hi!
It seems to me that some indexes of the target tokens are wrong.
I found problem in the next instances:
ru-ru: 0, 4
en-en: 2, 3
en-ru: 13
And may be the other pairs of languages have the same problem

Examples:
trial.en-en.2, **resolution**, NOUN, en, 17, en, 8, 'Ability to detect vertical movements , variations and dislocations of ground areas to a resolution of a **_few_** centimetres ;',
'Although Iraq was fully implementing all United Nations **resolutions** , it continued to suffer the devastating effects of the sanctions .'

trial.ru-ru.4, **год**, NOUN, ru, 3, ru, 12, 'В мае 1987 **года** на вершине горы Окубо в 4,1 км к западу от пусковой площадки был построен новый телеметрический центр.', 
'Так , более 100 000 пуэрториканцев приняли участие в демонстрации 14 июля **_прошлого_** года в знак протеста против присоединения .'

**Comment by federicomartelli** [comment]
Hi! 

Thank you very much for your feedback! We will fix this and will also provide new trial data in a new format ASAP!

Cheers, 
Federico
