### ISSUE TITLE
Regarding the mode of communication 

### ISSUE THREAD

**Issue by dipakamiitk** [SapienzaNLP/mcl-wic#3]
We wanted to know what is the main channel of communication for the task(We had few queries about the task) as we are unable to find the google group mentioned on the official SemEval page. Also, we wanted to know when will the training dataset be released.

**Comment by federicomartelli** [comment]
Hello! Please go to our [codalab competition](https://competitions.codalab.org/competitions/27054) and use the forum! We are about to release the training data! Thanks!
